name: Deploy xuecheng-plus-checkcode

on:
  push:
    branches: [ ending ]

  workflow_dispatch:

jobs:
  build-and-ending:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt' # 可以根据你的需求选择合适的JDK分发版

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          cache: 'maven'

      - name: Build with Maven
        working-directory: ./xuecheng-plus-checkcode
        run: mvn clean package -DskipTests

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          scp target/xuecheng-plus-checkcode.jar user@${{ secrets.HOST }}:/home/user/xuecheng-plus-checkcode.jar
          ssh root@${{ secrets.HOST }} << 'EOF'
            # 停止现有的服务
            docker stop xuecheng-plus-checkcode || true
            docker rm xuecheng-plus-checkcode || true

            # 运行新的容器
            docker run -d --name xuecheng-plus-checkcode -p 63075:63075 \
              -v /home/user/xuecheng-plus-checkcode.jar:/app/xuecheng-plus-checkcode.jar \
              openjdk:8-jdk-alpine \
              java -Dfile.encoding=UTF-8 -jar /app/xuecheng-plus-checkcode.jar
          EOF
