name: Docker Build and Deploy

on:
  push:
    branches:
      - ending

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false  # 不推送到任何注册表
          tags: local-image:latest  # 使用本地标签

      - name: Deploy to Local VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > id_rsa
          chmod 600 id_rsa
          scp -i id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r . user@your-vm-ip:/home/user/app
          ssh -i id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null user@your-vm-ip << 'EOF'
            cd /home/user/app
            docker build -t my-app:latest .
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 80:80 my-app:latest
          EOF
